# Настройки Build Battle

# Список тем для строительства
themes:
  - "Замок"
  - "Город будущего"
  - "Подводный мир"
  - "Космическая станция"
  - "Древний храм"
  - "Парк развлечений"
  - "Сказочный лес"
  - "Горный курорт"
  - "Тропический остров"
  - "Средневековая деревня"

# Временные интервалы для строительства (в минутах)
build-times:
  round1: 1
  round2: 3
  round3: 5

# Время на голосование (в минутах)
voting-time: 5

# Настройки команд
teams:
  max-players: 3
  total-teams: 8

# Настройки жюри
judges:
  min-score: 1
  max-score: 10

# Сообщения
messages:
  game-start: "&aИгра Build Battle началась!"
  round-start: "&eНачался раунд %round%! Время на строительство: %time% минут"
  voting-start: "&eНачалось голосование! У вас есть %time% минут на оценку построек"
  game-end: "&aИгра Build Battle завершена! Поздравляем победителей!" 